In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv('/content/house_prices.csv')

In [2]:
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [3]:
df['CRIM']

0      0.00632
1      0.02731
2      0.02729
3      0.03237
4      0.06905
        ...   
501    0.06263
502    0.04527
503    0.06076
504    0.10959
505    0.04741
Name: CRIM, Length: 506, dtype: float64

In [4]:
df['NOX']

0      0.538
1      0.469
2      0.469
3      0.458
4      0.458
       ...  
501    0.573
502    0.573
503    0.573
504    0.573
505    0.573
Name: NOX, Length: 506, dtype: float64

In [5]:
df['CRIM']*df['NOX']

0      0.003400
1      0.012808
2      0.012799
3      0.014825
4      0.031625
         ...   
501    0.035887
502    0.025940
503    0.034815
504    0.062795
505    0.027166
Length: 506, dtype: float64

소문자로 쓰면 스칼라  
소문자 볼드로 쓰면 벡터  
대문자로 쓰면 확률변수  
대문자 볼드는 행렬  


In [6]:
A = np.array([1,2,3,4,5,6,7,8])
print(A)

[1 2 3 4 5 6 7 8]


In [7]:
A1 = A.reshape(8,1)
print(A1)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [8]:
A1.shape

(8, 1)

수학에서는 열벡터가 기본인데 파이썬에선 행벡터가 기본

In [9]:
A4 = A.reshape(-1, 4)

print(A4)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
A5 = A.reshape(2, -1)
print(A5)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
A6 = A5.reshape(-1)
print(A6)

[1 2 3 4 5 6 7 8]


In [28]:
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [29]:
X = df[['CRIM', 'NOX', 'RM', 'AGE', 'TAX']]

In [30]:
X

CRIM    NOX     RM   AGE  TAX
0    0.00632  0.538  6.575  65.2  296
1    0.02731  0.469  6.421  78.9  242
2    0.02729  0.469  7.185  61.1  242
3    0.03237  0.458  6.998  45.8  222
4    0.06905  0.458  7.147  54.2  222
..       ...    ...    ...   ...  ...
501  0.06263  0.573  6.593  69.1  273
502  0.04527  0.573  6.120  76.7  273
503  0.06076  0.573  6.976  91.0  273
504  0.10959  0.573  6.794  89.3  273
505  0.04741  0.573  6.030  80.8  273

[506 rows x 5 columns]

In [31]:
X_t =X.T
X_t

0          1          2          3          4          5    \
CRIM    0.00632    0.02731    0.02729    0.03237    0.06905    0.02985   
NOX     0.53800    0.46900    0.46900    0.45800    0.45800    0.45800   
RM      6.57500    6.42100    7.18500    6.99800    7.14700    6.43000   
AGE    65.20000   78.90000   61.10000   45.80000   54.20000   58.70000   
TAX   296.00000  242.00000  242.00000  222.00000  222.00000  222.00000   

            6          7          8          9    ...       496        497  \
CRIM    0.08829    0.14455    0.21124    0.17004  ...    0.2896    0.26838   
NOX     0.52400    0.52400    0.52400    0.52400  ...    0.5850    0.58500   
RM      6.01200    6.17200    5.63100    6.00400  ...    5.3900    5.79400   
AGE    66.60000   96.10000  100.00000   85.90000  ...   72.9000   70.60000   
TAX   311.00000  311.00000  311.00000  311.00000  ...  391.0000  391.00000   

            498        499        500        501        502        503  \
CRIM    0.23912    0.17783    0.22438    0.06263    0.04527    0.06076   
NOX     0.58500    0.58500    0.58500    0.57300    0.57300    0.57300   
RM      6.01900    5.56900    6.02700    6.59300    6.12000    6.97600   
AGE    65.30000   73.50000   79.70000   69.10000   76.70000   91.00000   
TAX   391.00000  391.00000  391.00000  273.00000  273.00000  273.00000   

            504        505  
CRIM    0.10959    0.04741  
NOX     0.57300    0.57300  
RM      6.79400    6.03000  
AGE    89.30000   80.80000  
TAX   273.00000  273.00000  

[5 rows x 506 columns]

In [17]:

li=[1,2,3,4,5]
li2=[1],[2],[3],[4],[5]
ali = np.array(li)
print(ali.shape)
ali=np.transpose(ali)
print(ali.shape)
ali2=np.array(li2)
print(ali.shape, ali2.shape)

(5,)
(5,)
(5,) (5, 1)


In [32]:
X_t.dot(X)

CRIM            NOX            RM           AGE           TAX
CRIM  4.397034e+04    1226.123170  1.082195e+04  1.685150e+05  1.173073e+06
NOX   1.226123e+03     162.470380  1.751519e+03  2.045220e+04  1.211706e+05
RM    1.082195e+04    1751.519414  2.023460e+04  2.156702e+05  1.280740e+06
AGE   1.685150e+05   20452.201630  2.156702e+05  2.779615e+06  1.537874e+07
TAX   1.173073e+06  121170.623200  1.280740e+06  1.537874e+07  9.867314e+07

In [34]:
X_t@X

CRIM            NOX            RM           AGE           TAX
CRIM  4.397034e+04    1226.123170  1.082195e+04  1.685150e+05  1.173073e+06
NOX   1.226123e+03     162.470380  1.751519e+03  2.045220e+04  1.211706e+05
RM    1.082195e+04    1751.519414  2.023460e+04  2.156702e+05  1.280740e+06
AGE   1.685150e+05   20452.201630  2.156702e+05  2.779615e+06  1.537874e+07
TAX   1.173073e+06  121170.623200  1.280740e+06  1.537874e+07  9.867314e+07

$X^TX$ -> 공분산 행렬


## 행렬식  
정사각 행렬을 스칼라로 변환하는 함수  
정사각 행렬에만 해당, 행렬을 스칼라로 변환  

  
행렬식의 값은 그 도형의 **부피**

In [35]:
XtX = X_t@X

In [36]:
np.linalg.det(XtX)

7.914316577690132e+21

7.91e+21 = 7.91X$10^{21}$

행렬식 값도 중요하지만 0인지 아닌지가 제일 중요 -> 0이면 역행렬 구하기 불가능

$A^{-1} = {1\over a_{11}a_{22} - a_{12}a_{21}}$ 행렬  
분모가 행렬식

In [37]:
XtX_inv = np.linalg.inv(XtX)
print(XtX_inv)

[[ 4.07613803e-05  1.32526683e-04  4.76832932e-05 -1.01889386e-06
  -1.10744437e-06]
 [ 1.32526683e-04  3.44301609e-01 -1.30762150e-02 -8.56047279e-04
  -1.21234099e-04]
 [ 4.76832932e-05 -1.30762150e-02  9.05341934e-04  1.73338529e-05
   1.03814433e-06]
 [-1.01889386e-06 -8.56047279e-04  1.73338529e-05  5.35211609e-06
   4.19638894e-09]
 [-1.10744437e-06 -1.21234099e-04  1.03814433e-06  4.19638894e-09
   1.58047038e-07]]


In [38]:
XtX@XtX_inv

0             1             2             3             4
CRIM  1.000000e+00 -6.979357e-14  7.898703e-16 -1.089894e-15 -3.591367e-17
NOX  -1.610639e-17  1.000000e+00 -1.769057e-16 -3.317590e-17 -5.661019e-19
RM    2.097955e-16 -3.839137e-15  1.000000e+00 -1.547972e-16 -6.737559e-18
AGE  -2.352290e-15 -7.866743e-13  6.373451e-14  1.000000e+00  4.474723e-16
TAX  -4.461919e-15 -1.942029e-12  7.933252e-14 -7.646276e-15  1.000000e+00

In [39]:
XtX_inv @ XtX

CRIM           NOX            RM           AGE           TAX
0  1.000000e+00 -9.976309e-16 -1.049198e-14 -1.335187e-13 -7.702802e-13
1  1.450356e-13  1.000000e+00  1.243199e-13  2.092731e-12  1.189994e-11
2 -1.244734e-14 -1.753764e-15  1.000000e+00 -1.830795e-13 -1.243143e-12
3  2.089321e-16 -2.301382e-18  4.416128e-16  1.000000e+00  1.970463e-14
4  2.864010e-17  1.812250e-18  6.748655e-17  1.530867e-16  1.000000e+00

# 내적  
차원이랑 관련이 있는 것이 내적

$<u,v> = u^Tv = (u_1 u_2 u_3) \begin{pmatrix} u_1 & u_2 & u_3 \end{pmatrix}$

내적: 물체를 이동시킨 거리 (inner product)

추천 시스템도 내적으로 관련도를 계산하는 거임

In [40]:
crim = df['CRIM']
nox = df['NOX']

In [41]:
res = np.inner(crim, nox)
print(res)

1226.123170231


# 고윳값과 고유 벡터  
왜 중요?: 대각화에 쓰이기 때문

# 대각화 (diagonalization)  
$D = P^{-1}AP$  
여기서 P는 가역 행렬 -> 행렬식이 0이 아님  
여기서 A는 대칭 행렬


## 고윳값 분해  
고유 벡터: 핵심적인 뼈대를 나타냄  
고윳값: 고유 벡터의 길이  
가장 긴 것이 가장 중요  
  
원래 교유 벡터가 3개인데 2개로 차원 축소하면 2개로 생긴 평면에 나머지 정사영  
  
모든 차원은 고유벡터랑 관려이 있음 무적권
  
차원축소할 때는 정보손실을 없게 해줘야함  
짧은거 선택하면 로스가 커져서 긴 벡터들을 선택해서 차원축소

In [42]:
cov_x = X_t.dot(X)
cov_x

CRIM            NOX            RM           AGE           TAX
CRIM  4.397034e+04    1226.123170  1.082195e+04  1.685150e+05  1.173073e+06
NOX   1.226123e+03     162.470380  1.751519e+03  2.045220e+04  1.211706e+05
RM    1.082195e+04    1751.519414  2.023460e+04  2.156702e+05  1.280740e+06
AGE   1.685150e+05   20452.201630  2.156702e+05  2.779615e+06  1.537874e+07
TAX   1.173073e+06  121170.623200  1.280740e+06  1.537874e+07  9.867314e+07

In [43]:
e, v = np.linalg.eig(cov_x)

In [44]:
e #큰 순서대로 나오고 밑의 고유 벡터도 순서 같음 -> 순서 고려해서 차원축소 해주면 될듯

array([1.01109837e+08, 3.74919516e+05, 2.99553705e+04, 2.40312204e+03,
       2.90022330e+00])

In [45]:
v

array([[ 1.17248568e-02, -4.34541539e-02, -9.89273583e-01,
         1.38967257e-01, -3.78876853e-04],
       [ 1.21545113e-03,  3.97729110e-03,  5.48368537e-03,
         3.74537281e-02, -9.99274663e-01],
       [ 1.28461807e-02,  4.11504926e-02,  1.37240647e-01,
         9.88869506e-01,  3.79962757e-02],
       [ 1.54544362e-01,  9.86199762e-01, -4.66395497e-02,
        -3.66695593e-02,  2.48287726e-03],
       [ 9.87832003e-01, -1.54313263e-01,  1.72471505e-02,
        -8.81831838e-03,  3.51466736e-04]])

고윳값 분해는 정사각만!  
특이값 분해는 직사각에서도 ㄱㄴ (고윳값 분해 일반화 버전)

In [46]:
u, s, vt = np.linalg.svd(cov_x)

Singular Value Decomposition, SVD

In [47]:
u

array([[-1.17248568e-02,  4.34541539e-02,  9.89273583e-01,
        -1.38967257e-01, -3.78876853e-04],
       [-1.21545113e-03, -3.97729110e-03, -5.48368537e-03,
        -3.74537281e-02, -9.99274663e-01],
       [-1.28461807e-02, -4.11504926e-02, -1.37240647e-01,
        -9.88869506e-01,  3.79962757e-02],
       [-1.54544362e-01, -9.86199762e-01,  4.66395497e-02,
         3.66695593e-02,  2.48287726e-03],
       [-9.87832003e-01,  1.54313263e-01, -1.72471505e-02,
         8.81831838e-03,  3.51466736e-04]])

In [48]:
s

array([1.01109837e+08, 3.74919516e+05, 2.99553705e+04, 2.40312204e+03,
       2.90022330e+00])

In [49]:
vt

array([[-1.17248568e-02, -1.21545113e-03, -1.28461807e-02,
        -1.54544362e-01, -9.87832003e-01],
       [ 4.34541539e-02, -3.97729110e-03, -4.11504926e-02,
        -9.86199762e-01,  1.54313263e-01],
       [ 9.89273583e-01, -5.48368537e-03, -1.37240647e-01,
         4.66395497e-02, -1.72471505e-02],
       [-1.38967257e-01, -3.74537281e-02, -9.88869506e-01,
         3.66695593e-02,  8.81831838e-03],
       [-3.78876853e-04, -9.99274663e-01,  3.79962757e-02,
         2.48287726e-03,  3.51466736e-04]])

특이값 분해 할 때는 주의해야 함.  
차원은 고유값의 개수  


행렬에서는 ${A^TA}$가 제곱의 의미가 있음  
특이값: 루트 고윳값

In [50]:
u2, s2, vt2 = np.linalg.svd(X)

In [51]:
u2

array([[-0.03008946,  0.03086023,  0.01712144, ..., -0.00411115,
        -0.00427013, -0.00365704],
       [-0.02499491,  0.06652264,  0.00780423, ..., -0.05447262,
        -0.05387641, -0.05180949],
       [-0.02472231,  0.03790476,  0.0132068 , ..., -0.01726598,
        -0.01167245,  0.01252377],
       ...,
       [-0.02822706,  0.07823426,  0.00788495, ...,  0.99280739,
        -0.00687219, -0.00535758],
       [-0.02820076,  0.07548049,  0.00791964, ..., -0.00689953,
         0.99336613, -0.00536756],
       [-0.02806907,  0.0617432 ,  0.00995976, ..., -0.00551636,
        -0.00549819,  0.99463978]])

In [52]:
np.square(s2)

array([1.01109837e+08, 3.74919516e+05, 2.99553705e+04, 2.40312204e+03,
       2.90022330e+00])

In [53]:
s

array([1.01109837e+08, 3.74919516e+05, 2.99553705e+04, 2.40312204e+03,
       2.90022330e+00])